name: ci

on:
  push:
    branches: [ main ]
    paths:
    - "markdown_to_html/**"
    - ".github/workflows/ci.yaml"

  pull_request:
    branches: [ main ]
    paths:
    - "markdown_to_html/**"
    - ".github/workflows/ci.yaml"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: markdown_to_html
    
jobs:

  lint:
    name: "lint"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Rustfmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --all --all-features -- -D warnings